[package]
name = "grid"
version = "0.2.2"
authors = ["Armin Becher <armin.becher@gmai.com>"]
edition = "2018"
description = "Dynamic generic 2D data structure."
keywords = [ "2D", "array", "matrix", "data-structure", "2D-vector"]
categories = [ "science", "data-structures",]
readme = "README.md"
license = "MIT"
repository = "https://github.com/becheran/grid"
documentation = "https://docs.rs/grid"

[badges.gitlab]
repository = "becheran/grid_ci"
branch = "master"

[badges.maintenance]
status = "actively-developed"

[dev-dependencies]
criterion = "0.3.1"
rand="0.7.3"

[[bench]]
name = "benches"
harness = false
